# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(default='Text', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
