# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchapp', '0004_auto_20170329_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
